/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biomasa.view;

import biomasa.controller.ObradaDobavljaci;
import biomasa.model.Dobavljac;
import java.awt.Color;
import java.awt.Component;
import java.util.Arrays;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Đorđe
 */
public class Dobavljaci extends javax.swing.JInternalFrame {

    
    private ObradaDobavljaci obrada;
    private Dobavljac odabrano;
    
    /**
     * Creates new form Dobavljaci
     */
    public Dobavljaci() {
        initComponents();
        obrada=new ObradaDobavljaci();
        lista.setModel(new DefaultListModel<>());
       setTitle("Dobavljači: ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList();
        akcijaTrazi = new javax.swing.JButton();
        uvjet = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        akcijaDodaj = new javax.swing.JButton();
        akcijaPromijeni = new javax.swing.JButton();
        mjesto = new javax.swing.JTextField();
        akcijaPovratak = new javax.swing.JButton();
        akcijaObrisi = new javax.swing.JButton();
        naziv = new javax.swing.JTextField();
        oib = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 153, 0));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setTitle("Dobavljači");

        jPanel1.setBackground(new java.awt.Color(51, 153, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lista.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lista);

        akcijaTrazi.setBackground(new java.awt.Color(255, 102, 0));
        akcijaTrazi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        akcijaTrazi.setForeground(new java.awt.Color(255, 255, 255));
        akcijaTrazi.setText("Traži");
        akcijaTrazi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        akcijaTrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akcijaTraziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uvjet, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(akcijaTrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(202, 202, 202))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(akcijaTrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(uvjet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 153, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        akcijaDodaj.setBackground(new java.awt.Color(255, 102, 0));
        akcijaDodaj.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        akcijaDodaj.setForeground(new java.awt.Color(255, 255, 255));
        akcijaDodaj.setText("Dodaj");
        akcijaDodaj.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        akcijaDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akcijaDodajActionPerformed(evt);
            }
        });

        akcijaPromijeni.setBackground(new java.awt.Color(255, 102, 0));
        akcijaPromijeni.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        akcijaPromijeni.setForeground(new java.awt.Color(255, 255, 255));
        akcijaPromijeni.setText("Promijeni");
        akcijaPromijeni.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        akcijaPromijeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akcijaPromijeniActionPerformed(evt);
            }
        });

        akcijaPovratak.setBackground(new java.awt.Color(255, 102, 0));
        akcijaPovratak.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        akcijaPovratak.setForeground(new java.awt.Color(255, 255, 255));
        akcijaPovratak.setText("Povratak");
        akcijaPovratak.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        akcijaPovratak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akcijaPovratakActionPerformed(evt);
            }
        });

        akcijaObrisi.setBackground(new java.awt.Color(255, 102, 0));
        akcijaObrisi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        akcijaObrisi.setForeground(new java.awt.Color(255, 255, 255));
        akcijaObrisi.setText("Obriši");
        akcijaObrisi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        akcijaObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akcijaObrisiActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Oib:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Mjesto:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Naziv:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(akcijaPovratak, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(akcijaDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 40, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mjesto, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(oib, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(naziv)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(akcijaPromijeni, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(akcijaObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(akcijaPovratak, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(naziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(mjesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(oib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(akcijaDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(akcijaPromijeni, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(akcijaObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void akcijaPovratakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akcijaPovratakActionPerformed
        dispose();
    }//GEN-LAST:event_akcijaPovratakActionPerformed

    private void akcijaTraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akcijaTraziActionPerformed
        
         cistiPolja();
        
        List<Dobavljac> entiteti = obrada.uzmi(uvjet.getText());
        
        DefaultListModel <Dobavljac> m = new DefaultListModel<>();
        for (Dobavljac dobavljac : entiteti){
            
            m.addElement(dobavljac);
        }
        lista.setModel(m);
        
    }//GEN-LAST:event_akcijaTraziActionPerformed

    private void listaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaValueChanged
        
         reset();
        odabrano = (Dobavljac) lista.getSelectedValue();
        if(odabrano==null){
            return;
        }
        naziv.setText(odabrano.getNaziv());
        mjesto.setText(odabrano.getMjesto());
        oib.setText(odabrano.getOib());
        
    }//GEN-LAST:event_listaValueChanged

    private void akcijaDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akcijaDodajActionPerformed
        
        reset();
        if(naziv.getText().trim().isEmpty()){
           greska(naziv, "Obavezan naziv");
           return;
       }
        
        if(!obrada.provjeraNaziv(naziv.getText().trim())){
             greska(naziv, "Naziv postoji, odabarite drugi");
           return;
        }
        
         if(oib.getText().trim().isEmpty()){
           greska(oib, "OIB je obavezan!");
           return;
       }
        
        if(!obrada.provjeraOib(oib.getText().trim())){
             greska(oib, "OIB postoji u bazi, odabarite drugi");
           return;
        }
                                      
        Dobavljac d = new Dobavljac();
        d.setNaziv(naziv.getText().trim());        
        d.setMjesto(mjesto.getText().trim());
        d.setOib(oib.getText().trim());
        
        d=obrada.dodaj(d);
        
      
            DefaultListModel<Dobavljac> m =(DefaultListModel<Dobavljac>) lista.getModel();
            m.addElement(d);
        
        
    }//GEN-LAST:event_akcijaDodajActionPerformed

    private void akcijaPromijeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akcijaPromijeniActionPerformed
        
        if(odabrano==null){
    return;
}       
        reset();
        
//kontrole   
        
         if(naziv.getText().trim().isEmpty()){
           greska(naziv, "Obavezan naziv");
           return;
       }
         
         if(!odabrano.getNaziv().equals(naziv.getText().trim())){
            if(!obrada.provjeraNaziv(naziv.getText().trim())){
                 greska(naziv, "Naziv postoji, odaberite drugi");
                return;
            }
            
        }
                
           if(oib.getText().trim().isEmpty()){
           greska(oib, "Obavezan oib");
           return;
       }
           
         if(!odabrano.getOib().equals(oib.getText().trim())){
            if(!obrada.provjeraOib(oib.getText().trim())){
                 greska(oib, "OIB postoji, odaberite drugi");
                return;
            }
            
        }
        
        odabrano.setNaziv(naziv.getText().trim());
        odabrano.setMjesto(mjesto.getText().trim());
        odabrano.setOib(oib.getText().trim());
       
        
        //promjena u bazi
        if(!obrada.promijeni(odabrano)){
            return;
        }
               
        lista.repaint();
                                                
        
    }//GEN-LAST:event_akcijaPromijeniActionPerformed

    private void akcijaObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akcijaObrisiActionPerformed
       
         odabrano = (Dobavljac) lista.getSelectedValue();
        if(odabrano==null){
            return;
        }
       if(JOptionPane.showConfirmDialog(getParent(), "Jeste li sigurni da želite obrisati " + odabrano.getNaziv() + "?","Brisanje dobavljača",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE)==JOptionPane.NO_OPTION){
            return;
        }
       
       if(!obrada.obrisi(odabrano)){
           return;
       }
       
       DefaultListModel<Dobavljac> m =   (DefaultListModel<Dobavljac>) lista.getModel();
       m.removeElement(odabrano);
       lista.repaint();
       cistiPolja();
    }//GEN-LAST:event_akcijaObrisiActionPerformed

    private void cistiPolja(){
        naziv.setText("");
        mjesto.setText("");
        oib.setText("");
    }
    
        private void reset() {
       
        for (Component c : this.getContentPane().getComponents()) {
            if (c instanceof JTextField || c instanceof JPasswordField){
                JComponent jc = (JComponent) c;
                jc.setBackground(Color.white);
                jc.setToolTipText("");
            }
        }
    }
        
         private void greska(JComponent komponenta, String obavijest){
           komponenta.setBackground(Color.yellow);
           komponenta.requestFocus();
           komponenta.setToolTipText(obavijest);
           
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton akcijaDodaj;
    private javax.swing.JButton akcijaObrisi;
    private javax.swing.JButton akcijaPovratak;
    private javax.swing.JButton akcijaPromijeni;
    private javax.swing.JButton akcijaTrazi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lista;
    private javax.swing.JTextField mjesto;
    private javax.swing.JTextField naziv;
    private javax.swing.JTextField oib;
    private javax.swing.JTextField uvjet;
    // End of variables declaration//GEN-END:variables
}
