/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biomasa.view;


import biomasa.model.Operater;
import biomasa.utility.Dodaci;
import java.beans.PropertyVetoException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Đorđe
 */
public class Izbornik extends javax.swing.JFrame {

    /**
     * Creates new form Izbornik
     */
    public Izbornik() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Biomasa d.o.o "
                + Dodaci.getOperater().getImePrezime());
        
        if (Dodaci.getOperater().getUloga().equals(Operater.ADMINISTRATOR)) {
            akcijaOperateri.setVisible(true);
        } else {
            akcijaOperateri.setVisible(false);
        }
        
       Sat t = new Sat(datumVrijeme);
        t.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        akcijaDovozi = new javax.swing.JButton();
        akcijaOperateri = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        dobavljaci = new javax.swing.JButton();
        akcijaStovarista = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        akcijaVozaci = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        akcijaPrijevoznici = new javax.swing.JButton();
        akcijaKamioni = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        datumVrijeme = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        akcijaIzlaz = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 153, 0));
        setMaximumSize(new java.awt.Dimension(673, 439));

        jDesktopPane1.setBackground(new java.awt.Color(51, 153, 0));
        jDesktopPane1.setMaximumSize(new java.awt.Dimension(673, 393));
        jDesktopPane1.setMinimumSize(new java.awt.Dimension(673, 393));
        jDesktopPane1.setName(""); // NOI18N

        akcijaDovozi.setBackground(new java.awt.Color(255, 102, 0));
        akcijaDovozi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        akcijaDovozi.setForeground(new java.awt.Color(255, 255, 255));
        akcijaDovozi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Kamion1.png"))); // NOI18N
        akcijaDovozi.setText("Dovoz sirovine");
        akcijaDovozi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        akcijaDovozi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        akcijaDovozi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akcijaDovoziActionPerformed(evt);
            }
        });

        akcijaOperateri.setBackground(new java.awt.Color(255, 102, 0));
        akcijaOperateri.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        akcijaOperateri.setForeground(new java.awt.Color(255, 255, 255));
        akcijaOperateri.setText("Operateri");
        akcijaOperateri.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        akcijaOperateri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akcijaOperateriActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BIOMASA (1).png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(51, 153, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        dobavljaci.setBackground(new java.awt.Color(255, 102, 0));
        dobavljaci.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dobavljaci.setForeground(new java.awt.Color(255, 255, 255));
        dobavljaci.setText("Dobavljači");
        dobavljaci.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dobavljaci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobavljaciActionPerformed(evt);
            }
        });

        akcijaStovarista.setBackground(new java.awt.Color(255, 102, 0));
        akcijaStovarista.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        akcijaStovarista.setForeground(new java.awt.Color(255, 255, 255));
        akcijaStovarista.setText("Stovarišta");
        akcijaStovarista.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        akcijaStovarista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akcijaStovaristaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dobavljaci, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(akcijaStovarista, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(akcijaStovarista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1))
                    .addComponent(dobavljaci, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(51, 153, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        akcijaVozaci.setBackground(new java.awt.Color(255, 102, 0));
        akcijaVozaci.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        akcijaVozaci.setForeground(new java.awt.Color(255, 255, 255));
        akcijaVozaci.setText("Vozači");
        akcijaVozaci.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        akcijaVozaci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akcijaVozaciActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("<html>Podaci o <br> prijevoznicima</html>");

        akcijaPrijevoznici.setBackground(new java.awt.Color(255, 102, 0));
        akcijaPrijevoznici.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        akcijaPrijevoznici.setForeground(new java.awt.Color(255, 255, 255));
        akcijaPrijevoznici.setText("Prijevoznici");
        akcijaPrijevoznici.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        akcijaPrijevoznici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akcijaPrijevozniciActionPerformed(evt);
            }
        });

        akcijaKamioni.setBackground(new java.awt.Color(255, 102, 0));
        akcijaKamioni.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        akcijaKamioni.setForeground(new java.awt.Color(255, 255, 255));
        akcijaKamioni.setText("Kamioni");
        akcijaKamioni.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        akcijaKamioni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akcijaKamioniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(akcijaVozaci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(akcijaPrijevoznici, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(akcijaKamioni, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(akcijaKamioni, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(akcijaVozaci, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(akcijaPrijevoznici, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(akcijaOperateri, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(akcijaDovozi, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(91, 91, 91))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(akcijaOperateri, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(49, 49, 49)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(akcijaDovozi, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
        );
        jDesktopPane1.setLayer(akcijaDovozi, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(akcijaOperateri, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jToolBar1.setBackground(new java.awt.Color(204, 204, 204));
        jToolBar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jToolBar1.setRollover(true);
        jToolBar1.setAutoscrolls(true);
        jToolBar1.setBorderPainted(false);
        jToolBar1.add(datumVrijeme);

        jMenuBar1.setBackground(new java.awt.Color(255, 102, 0));
        jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        jMenu3.setBackground(new java.awt.Color(255, 102, 0));
        jMenu3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu3.setForeground(new java.awt.Color(255, 255, 255));
        jMenu3.setText("Biomasa");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        jMenuItem5.setBackground(new java.awt.Color(255, 102, 0));
        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jMenuItem5.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem5.setText("Ustroj");
        jMenu3.add(jMenuItem5);

        akcijaIzlaz.setBackground(new java.awt.Color(255, 102, 0));
        akcijaIzlaz.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        akcijaIzlaz.setForeground(new java.awt.Color(255, 255, 255));
        akcijaIzlaz.setText("Izlaz");
        akcijaIzlaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akcijaIzlazActionPerformed(evt);
            }
        });
        jMenu3.add(akcijaIzlaz);

        jMenuBar1.add(jMenu3);

        jMenu4.setBackground(new java.awt.Color(255, 102, 0));
        jMenu4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu4.setForeground(new java.awt.Color(255, 255, 255));
        jMenu4.setText("Pomoć");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMenuItem4.setBackground(new java.awt.Color(255, 102, 0));
        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jMenuItem4.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem4.setText("O nama");
        jMenu4.add(jMenuItem4);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jDesktopPane1.getAccessibleContext().setAccessibleParent(jDesktopPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void akcijaDovoziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akcijaDovoziActionPerformed
        
        Dovozi dc = new Dovozi();
        jDesktopPane1.add(dc);
        try {
            dc.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Izbornik.class.getName()).log(Level.SEVERE, null, ex);
        }
        dc.show();
        
    }//GEN-LAST:event_akcijaDovoziActionPerformed

    private void akcijaPrijevozniciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akcijaPrijevozniciActionPerformed
        
        Prijevoznici pc = new Prijevoznici();
        jDesktopPane1.add(pc);
        try {
            pc.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Izbornik.class.getName()).log(Level.SEVERE, null, ex);
        }
        pc.show();
        
    }//GEN-LAST:event_akcijaPrijevozniciActionPerformed

    private void akcijaStovaristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akcijaStovaristaActionPerformed
        
         Stovarista sc = new Stovarista();
        jDesktopPane1.add(sc);
        try {
            sc.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Izbornik.class.getName()).log(Level.SEVERE, null, ex);
        }
        sc.show();
        
    }//GEN-LAST:event_akcijaStovaristaActionPerformed

    private void akcijaVozaciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akcijaVozaciActionPerformed
       
         Vozaci vc = new Vozaci();
        jDesktopPane1.add(vc);
        try {
            vc.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Izbornik.class.getName()).log(Level.SEVERE, null, ex);
        }
        vc.show();
        
    }//GEN-LAST:event_akcijaVozaciActionPerformed

    private void dobavljaciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobavljaciActionPerformed
        
        Dobavljaci dc = new Dobavljaci();
        jDesktopPane1.add(dc);
        try {
            dc.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Izbornik.class.getName()).log(Level.SEVERE, null, ex);
        }
        dc.show();
        
    }//GEN-LAST:event_dobavljaciActionPerformed

    private void akcijaOperateriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akcijaOperateriActionPerformed
       
         Operateri oc = new Operateri();
        jDesktopPane1.add(oc);
        try {
            oc.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Izbornik.class.getName()).log(Level.SEVERE, null, ex);
        }
        oc.show();
    }//GEN-LAST:event_akcijaOperateriActionPerformed

    private void akcijaIzlazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akcijaIzlazActionPerformed
       dispose();
        
    }//GEN-LAST:event_akcijaIzlazActionPerformed

    private void akcijaKamioniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akcijaKamioniActionPerformed
        
       Kamioni oc = new Kamioni();
        jDesktopPane1.add(oc);
        try {
            oc.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Izbornik.class.getName()).log(Level.SEVERE, null, ex);
        }
        oc.show();
    }//GEN-LAST:event_akcijaKamioniActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton akcijaDovozi;
    private javax.swing.JMenuItem akcijaIzlaz;
    private javax.swing.JButton akcijaKamioni;
    private javax.swing.JButton akcijaOperateri;
    private javax.swing.JButton akcijaPrijevoznici;
    private javax.swing.JButton akcijaStovarista;
    private javax.swing.JButton akcijaVozaci;
    private javax.swing.JLabel datumVrijeme;
    private javax.swing.JButton dobavljaci;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
