/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biomasa.view;

import biomasa.controller.ObradaKamioni;
import biomasa.controller.ObradaPrijevoznici;
import biomasa.controller.ObradaVozaci;
import biomasa.model.Kamion;
import biomasa.model.Prijevoznik;
import biomasa.model.Vozac;
import java.awt.Color;
import java.awt.Component;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Đorđe
 */
public class Kamioni extends javax.swing.JInternalFrame {

    private ObradaKamioni obrada;
    private Kamion odabrano;
    /**
     * Creates new form Kamioni
     */
    public Kamioni() {
        
        initComponents();
        obrada=new ObradaKamioni();
        lista.setModel(new DefaultListModel<Kamion>());
       setTitle("Kamioni po prijevoznicima: ");
        
        ObradaPrijevoznici op = new ObradaPrijevoznici();
        List<Prijevoznik> lp = op.uzmi("");
        DefaultComboBoxModel<Prijevoznik> mp = new DefaultComboBoxModel<>();
        for (Prijevoznik l : lp) {
            mp.addElement(l);
        }
          
        prijevoznik.setModel(mp);
        
       
        DefaultComboBoxModel<Vozac> mv = new DefaultComboBoxModel<>();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList();
        akcijaTrazi = new javax.swing.JButton();
        uvjet = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        akcijaDodaj = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        vozac = new javax.swing.JComboBox();
        akcijaObrisi = new javax.swing.JButton();
        akcijaPromijeni = new javax.swing.JButton();
        prijevoznik = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        nosivost = new javax.swing.JTextField();
        akcijaPovratak = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        registracija = new javax.swing.JTextField();

        setBackground(new java.awt.Color(51, 153, 0));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setTitle("Kamioni");

        jPanel1.setBackground(new java.awt.Color(51, 153, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lista.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lista);

        akcijaTrazi.setBackground(new java.awt.Color(255, 102, 0));
        akcijaTrazi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        akcijaTrazi.setForeground(new java.awt.Color(255, 255, 255));
        akcijaTrazi.setText("Traži");
        akcijaTrazi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        akcijaTrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akcijaTraziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(akcijaTrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addComponent(uvjet, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(akcijaTrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(uvjet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 153, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        akcijaDodaj.setBackground(new java.awt.Color(255, 102, 0));
        akcijaDodaj.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        akcijaDodaj.setForeground(new java.awt.Color(255, 255, 255));
        akcijaDodaj.setText("Dodaj");
        akcijaDodaj.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        akcijaDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akcijaDodajActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Nosivost(t):");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("( broj, npr. 100 )");

        akcijaObrisi.setBackground(new java.awt.Color(255, 102, 0));
        akcijaObrisi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        akcijaObrisi.setForeground(new java.awt.Color(255, 255, 255));
        akcijaObrisi.setText("Obriši");
        akcijaObrisi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        akcijaObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akcijaObrisiActionPerformed(evt);
            }
        });

        akcijaPromijeni.setBackground(new java.awt.Color(255, 102, 0));
        akcijaPromijeni.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        akcijaPromijeni.setForeground(new java.awt.Color(255, 255, 255));
        akcijaPromijeni.setText("Promijeni");
        akcijaPromijeni.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        akcijaPromijeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akcijaPromijeniActionPerformed(evt);
            }
        });

        prijevoznik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prijevoznikActionPerformed(evt);
            }
        });
        prijevoznik.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                prijevoznikPropertyChange(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Registracija:");

        akcijaPovratak.setBackground(new java.awt.Color(255, 102, 0));
        akcijaPovratak.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        akcijaPovratak.setForeground(new java.awt.Color(255, 255, 255));
        akcijaPovratak.setText("Povratak");
        akcijaPovratak.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        akcijaPovratak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akcijaPovratakActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Vozač:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Prijevoznik:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(akcijaPovratak, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(akcijaDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(registracija, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(vozac, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(prijevoznik, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(nosivost, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(akcijaPromijeni, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(akcijaObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(akcijaPovratak, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(registracija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(prijevoznik))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(vozac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nosivost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(akcijaDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(akcijaPromijeni, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(akcijaObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void akcijaPovratakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akcijaPovratakActionPerformed
        
        dispose();
    }//GEN-LAST:event_akcijaPovratakActionPerformed

    private void akcijaTraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akcijaTraziActionPerformed
        
        cistiPolja();
        
        List<Kamion> entiteti = obrada.uzmi(uvjet.getText());
        
        DefaultListModel <Kamion> m = new DefaultListModel<>();
        for (Kamion kamion : entiteti){
            
            m.addElement(kamion);
        }
        lista.setModel(m);
    }//GEN-LAST:event_akcijaTraziActionPerformed

    private void listaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaValueChanged
        
        reset();
        odabrano = (Kamion) lista.getSelectedValue();
        if(odabrano==null){
            return;
        }
        registracija.setText(odabrano.getRegistracija());
        
        DefaultComboBoxModel<Prijevoznik> mp = (DefaultComboBoxModel<Prijevoznik>) prijevoznik.getModel();
        for(int i=0;i<mp.getSize();i++){
            if(mp.getElementAt(i).getSifra()==odabrano.getPrijevoznik().getSifra()){
                prijevoznik.setSelectedIndex(i);
                break;
            }
        }
        
        DefaultComboBoxModel<Vozac> mv = (DefaultComboBoxModel<Vozac>) vozac.getModel();
        for(int i=0;i<mv.getSize();i++){
            if(mv.getElementAt(i).getSifra()==odabrano.getVozac().getSifra()){
                vozac.setSelectedIndex(i);
                break;
            }
        }
        
       nosivost.setText(String.valueOf(odabrano.getNosivost()));
    }//GEN-LAST:event_listaValueChanged

    private void akcijaDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akcijaDodajActionPerformed
        
        reset();
        Kamion k = new Kamion();
        if(registracija.getText().trim().isEmpty()){
           greska(registracija, "Registracija je obavezna");
           return;
       }
        
        if(!obrada.provjeraRegistracija(registracija.getText().trim())){
             greska(registracija, "Taj kamion je već u bazi podataka!");
           return;
        }
        
        k.setRegistracija(registracija.getText().trim());
        
        k.setPrijevoznik((Prijevoznik) prijevoznik.getSelectedItem());
        k.setVozac((Vozac)vozac.getSelectedItem());
       
        try {
            k.setNosivost(Integer.parseInt(nosivost.getText().trim()));
        } catch (Exception e) {
            greska(nosivost, "broj nije dobrog formata");
            return;
        }                             
        
        k=obrada.dodaj(k);
        
      
            DefaultListModel<Kamion> m =(DefaultListModel<Kamion>) lista.getModel();
            m.addElement(k);
        
        
    }//GEN-LAST:event_akcijaDodajActionPerformed

    private void akcijaPromijeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akcijaPromijeniActionPerformed
        
         if(odabrano==null){
    return;
}       
        reset();
        
//kontrole   
        
      if(registracija.getText().trim().isEmpty()){
           greska(registracija, "Registracija je obavezna");
           return;
       }
         
        if(!obrada.provjeraRegistracija(registracija.getText().trim())){
             greska(registracija, "Taj kamion je već u bazi podataka!");
           return;
        }
                                  
        odabrano.setRegistracija(registracija.getText().trim());
        odabrano.setPrijevoznik((Prijevoznik) prijevoznik.getSelectedItem());
        odabrano.setVozac((Vozac)vozac.getSelectedItem());
       
         try {
            odabrano.setNosivost(Integer.parseInt(nosivost.getText().trim()));
        } catch (Exception e) {
            greska(nosivost, "broj nije dobrog formata");
            return;
        }      
         
        //promjena u bazi
        if(!obrada.promijeni(odabrano)){
            return;
        }
               
        lista.repaint();
                                                
        
        
    }//GEN-LAST:event_akcijaPromijeniActionPerformed

    private void akcijaObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akcijaObrisiActionPerformed
        
         odabrano = (Kamion) lista.getSelectedValue();
        if(odabrano==null){
            return;
        }
       if(JOptionPane.showConfirmDialog(getParent(), "Jeste li sigurni da želite obrisati kamion " + odabrano.getRegistracija()+ ", "+ odabrano.getPrijevoznik().getNaziv() + "?","Brisanje kamiona",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE)==JOptionPane.NO_OPTION){
            return;
        }
       
       if(!obrada.obrisi(odabrano)){
           return;
       }
       
       DefaultListModel<Kamion> m =   (DefaultListModel<Kamion>) lista.getModel();
       m.removeElement(odabrano);
       lista.repaint();
       cistiPolja();
        
    }//GEN-LAST:event_akcijaObrisiActionPerformed

    private void prijevoznikPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_prijevoznikPropertyChange
       
    }//GEN-LAST:event_prijevoznikPropertyChange

    private void prijevoznikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prijevoznikActionPerformed
       Prijevoznik p = (Prijevoznik) prijevoznik.getSelectedItem();
        if(p==null){
            return;
        }
        DefaultComboBoxModel<Vozac> m = new DefaultComboBoxModel<>();
        for (Vozac v : p.getVozaci()) {
            m.addElement(v);
        }
        vozac.setModel(m);
    }//GEN-LAST:event_prijevoznikActionPerformed

    private void cistiPolja(){
        registracija.setText("");
        nosivost.setText("");
        
    }
    
        private void reset() {
       
        for (Component c : this.getContentPane().getComponents()) {
            if (c instanceof JTextField ){
                JComponent jc = (JComponent) c;
                jc.setBackground(Color.white);
                jc.setToolTipText("");
            }
        }
    }
        
         private void greska(JComponent komponenta, String obavijest){
           komponenta.setBackground(Color.yellow);
           komponenta.requestFocus();
           komponenta.setToolTipText(obavijest);
           
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton akcijaDodaj;
    private javax.swing.JButton akcijaObrisi;
    private javax.swing.JButton akcijaPovratak;
    private javax.swing.JButton akcijaPromijeni;
    private javax.swing.JButton akcijaTrazi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lista;
    private javax.swing.JTextField nosivost;
    private javax.swing.JComboBox prijevoznik;
    private javax.swing.JTextField registracija;
    private javax.swing.JTextField uvjet;
    private javax.swing.JComboBox vozac;
    // End of variables declaration//GEN-END:variables
}
